// Consolidated: re-export QSR Objective Marker system
export {
  ObjectiveMarkerType,
  ObjectiveMarkerKind,
  ObjectiveMarkerPhysicalSize,
  MarkerState,
  SwitchState,
  ObjectiveMarker,
  ObjectiveMarkerConfig,
  ObjectiveMarkerManager,
  createObjectiveMarker,
  createStandardMarkers,
  createBeaconMarkers,
  createIntelMarkers,
  isSwitchMarker,
  isLockMarker,
  isKeyMarker,
  isIdeaMarker,
  isPhysicalMarker,
  getMarkerPhysicalSize,
  getMarkerHandsRequired,
  getMarkerLadenLevel,
  getMarkerAcquireApCost,
} from '../mission/objective-markers';
